# Basic
title: 狷墨居
subtitle: 狷墨居主人的个人天地
welcome_message: 墨学爱好者，马克思主义者，掌中戏原教旨主义者，古典乐、新世纪乐、戏曲听众，C/C++程序员。
description: 风含翠篠娟娟净，雨裛红蕖冉冉香
creator: <a href="https://github.com/linusboyle">@狷墨居主人</a>

url: "https://linusboyle.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: BiliBili, description: Bilibili homepage, url: 'https://space.bilibili.com/18177890'}
    - {title: About Me, description: description of myself in Chinese, url: '/2018/07/About-Me'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#comment:
    #disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 5370899507
    github: linusboyle
    #twitter: onevcat
    #facebook: boyle.linus.5
    gplus: 106875862514148562818
    mail: hzl17@mails.tsinghua.edu.cn

# Google Analytics
ga:
     id: UA-121698925-1
     host: linusboyle.github.io
